[package]
name = "mini_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
bincode = "*"
serde = "~1.0.126"
serde_derive = "~1.0.126"
